---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
  labels:
    provider: "fabric8"
    project: "elasticsearch"
    version: "2.2.297"
    group: "io.fabric8.devops.apps"
  name: "es-data"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
