---
apiVersion: "extensions/v1beta1"
kind: "DaemonSet"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/fluentd/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "fluentd"
    version: "2.2.297"
    group: "io.fabric8.devops.apps"
  name: "fluentd"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        provider: "fabric8"
        project: "fluentd"
        version: "2.2.297"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "ELASTICSEARCH_HOST"
          value: "elasticsearch"
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        image: "fabric8/fluentd-kubernetes:v1.19"
        name: "fluentd"
        ports:
        - containerPort: 24231
          name: "scrape"
        resources:
          limits:
            cpu: "100m"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/log"
          name: "varlog"
        - mountPath: "/var/lib/docker/containers"
          name: "defaultdocker"
          readOnly: true
        - mountPath: "/mnt/ephemeral/docker/containers"
          name: "awsdocker"
          readOnly: true
        - mountPath: "/mnt/sda1/var/lib/docker/containers"
          name: "minikubedocker"
          readOnly: true
      serviceAccountName: "fluentd"
      volumes:
      - hostPath:
          path: "/var/log"
        name: "varlog"
      - hostPath:
          path: "/var/lib/docker/containers"
        name: "defaultdocker"
      - hostPath:
          path: "/mnt/ephemeral/docker/containers"
        name: "awsdocker"
      - hostPath:
          path: "/mnt/sda1/var/lib/docker/containers"
        name: "minikubedocker"
