---
name: "kibana"
home: "http://fabric8.io/kibana/"
sources:
- "http://github.com/fabric8io/fabric8-devops/kibana"
version: "2.2.297"
description: "Awesome front-end for Elasticsearch"
maintainers:
- name: "Fabric8 Development Team"
  email: "fabric8@googlegroups.com"
icon: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
