---
- name: include inventory variables
  include_vars: /inventory.yml

- name: set proxy vars
  set_fact:
    proxy_env:
      http_proxy: "{{ proxy_info.http_proxy }}"
      https_proxy: "{{ proxy_info.https_proxy }}"
      no_proxy: "{{ proxy_info.no_proxy }},{{ machines.master.ip }}"
  when: proxy_info.use_proxy

- name: no proxy case
  set_fact:
    proxy_env:
      mock: ""
  when: not proxy_info.use_proxy

- name: setup apt proxy config
  template:
    src: "roles/k8s/templates/apt.conf.j2"
    dest: /etc/apt/apt.conf
    mode: 0644
  become: yes
  when: proxy_info.use_proxy

- name: setup docker machines (proxy)
  shell: 'docker-machine create -d generic  --generic-ip-address={{ ansible_ssh_host }} --generic-ssh-key ~/.ssh/id_rsa --generic-ssh-user {{ ssh_info.user }} --engine-env HTTP_PROXY="{{ proxy_info.http_proxy }}" --engine-env HTTPS_PROXY="{{ proxy_info.https_proxy }}" --engine-env NO_PROXY="{{ proxy_info.no_proxy }}"  {{ inventory_hostname }}'
  environment: "{{ proxy_env }}"
  when: proxy_info.use_proxy
  delegate_to: 127.0.0.1

- name: setup docker machines
  shell: 'docker-machine create -d generic  --generic-ip-address={{ ansible_ssh_host }} --generic-ssh-key ~/.ssh/id_rsa --generic-ssh-user {{ ssh_info.user }} {{ inventory_hostname }}'
  environment: "{{ proxy_env }}"
  when: not proxy_info.use_proxy
  delegate_to: 127.0.0.1

#- name: remove the proxy env file
#  file: path=~/.ssh/environment state=absent
 
