---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.297"
    fabric8.io/build-id: "4"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/kibana/src/main/fabric8/icon.svg"
    fabric8.io/git-branch: "release-v2.2.297"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
  labels:
    provider: "fabric8"
    project: "kibana"
    version: "2.2.297"
    group: "io.fabric8.devops.apps"
  name: "kibana"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "kibana"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.297"
        fabric8.io/build-id: "4"
        fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
        fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/kibana/src/main/fabric8/icon.svg"
        fabric8.io/git-branch: "release-v2.2.297"
        fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
      labels:
        provider: "fabric8"
        project: "kibana"
        version: "2.2.297"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elasticsearch:9200"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/kibana4:v4.5.3"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 5601
        name: "kibana"
        readinessProbe:
          httpGet:
            path: "/"
            port: 5601
          initialDelaySeconds: 5
        securityContext:
          privileged: false
      - env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elasticsearch:9200"
        image: "fabric8/kibana-config:2.2.297"
        name: "logstash-template"
